name: CI-Jest-Test-Example

on:
  push:
    branches:
      - '!main'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'develop'
      - 'feature/**'
jobs:
  sonarcloud:
      name: sonar-scan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Test and coverage
          run: yarn jest
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
